### ISSUE TITLE
when using with drf_yasg swagger page will trigger a KeyError exception

### ISSUE THREAD

**Issue by jeffrey4l** [alanjds/drf-nested-routers#227]
when inspecting nested resource schema for swagger generation, a KeyError exception is raised like below.

```
WARNING 2021-05-05 22:02:33,211 base 621695 140139741308480 view's RouteViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "/home/jeffrey/.dotfiles/virtualenvs/swapi/lib/python3.9/site-packages/drf_yasg/inspectors/base.py", line 42, in call_view_method
    return view_method()
  File ".../swapi/swapi/route/views.py", line 140, in get_queryset
    return super().get_queryset()
  File ".../swapi/swapi/route/utils.py", line 207, in get_queryset
    return super().get_queryset()
  File ".../lib/python3.9/site-packages/rest_framework_nested/viewsets.py", line 52, in get_queryset
    orm_filters[field_name] = self.kwargs[query_param]
KeyError: 'vpn_pk'
```

**Comment by jeffrey4l** [comment]
a workaround is use a custom NestedViewSetMixin

```python
class NestedViewSetMixin(nested_viewsets.NestedViewSetMixin):

    def get_queryset(self):
        if getattr(self, 'swagger_fake_view', False):
           return generics.GenericAPIView.get_queryset(self)
        return super().get_queryset()
```

**Comment by jeffrey4l** [comment]
#228  is merged. we can close this issue.
